#!/bin/bash
set -e

source ${OPENSHIFT_REPO_DIR}/misc/openshift/config
source ${OPENSHIFT_REPO_DIR}/misc/openshift/func

env | sed 's/[\%]/\\&/g;s/\([^=]*\)=\(.*\)/s%${\1}%\2%/' > ${OPENSHIFT_TMP_DIR}/sed.script

function expand_env_vars() {
    local SRC=$1
    local DEST=$2
    cat $SRC | sed -f $OPENSHIFT_TMP_DIR/sed.script > $DEST
}

function copy_config() {
    msg_info "Copying nginx config..."
    expand_env_vars ${CONFIG_TPL_DIR}/nginx.conf ${NGINX_DIR}/conf/nginx.conf
    msg_success "Copying nginx config... done"
}

copy_config
