#!/bin/bash

# Helper functions used by several scripts.
export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_DIY_DIR}/runtime/
export OPENSHIFT_RUN_DIR=${OPENSHIFT_DIY_DIR}/run/
export OPENSHIFT_BIN=${OPENSHIFT_RUNTIME_DIR}/bin/

export PATH=${OPENSHIFT_BIN}:$PATH

# When using rockmongo this is set and can cause strange errors here
export PHPRC=${OPENSHIFT_RUNTIME_DIR}/etc/php5/

ROOT_DIR=${OPENSHIFT_RUNTIME_DIR}
BUILD_DIR=${OPENSHIFT_TMP_DIR}/build

CONDA_DIR="${OPENSHIFT_DATA_DIR}/conda"
export CONDA_DIR

NGINX_VERSION="1.9.12"
NGINX_PCRE_VERSION="8.38"
NGINX_ZLIB_VERSION="1.2.8"
NGINX_DIR="${OPENSHIFT_DATA_DIR}/nginx"
export NGINX_DIR

REQUIREMENTS_FILE="${OPENSHIFT_REPO_DIR}/requirements.txt"
CONFIG_TPL_DIR="${OPENSHIFT_REPO_DIR}/misc/conf"
